In [4]:
from scipy.ndimage import imread
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from math import pi
import os

In [5]:
img = imread("negatives/n11.png")

In [183]:
def read_images(path):
    return [imread(path + name) for name in sorted(os.listdir(path)) if name.endswith(".png")]

def brightness():
    pass

def show_images(images):
    def subplot(grid, image, index, cmap=None):
        subplot = plt.subplot(grid[i*4+index])
        subplot.imshow(img, cmap=cmap)
        subplot.axis('off')
    
    grid = gridspec.GridSpec(len(images), 4, hspace=0., wspace=0., left=0, top=1, bottom=0, right=1)
    plt.figure(figsize=(100, 100))
    for i in range(len(images)):
        subplot(grid, images[i], 0)
        subplot(grid, images[i][:,:,0], 1, 'gray')
        subplot(grid, images[i][:,:,1], 2, 'gray')
        subplot(grid, images[i][:,:,2], 3, 'gray')
    grid.update(hspace=0.)
    plt.show()

def features(images):
    return np.array([np.average(np.average(image, axis=0), axis=0) for image in images])


In [184]:
negatives = np.array(read_images("negatives/"))
positives = np.array(read_images("positives/"))

In [185]:
print(positives.shape)
print(features(positives))


(30, 24, 24, 3)
[[ 180.38888889  150.19791667  150.64236111]
 [ 187.56423611  153.67013889  156.18055556]
 [ 164.48090278  138.69444444  138.79340278]
 [ 188.98090278  153.51388889  151.88541667]
 [ 172.62673611  135.61284722  143.20659722]
 [ 184.54513889  149.55208333  150.48784722]
 [ 177.12326389  142.42013889  142.25      ]
 [ 181.09548611  145.17534722  146.55729167]
 [ 162.32291667  131.94618056  140.87326389]
 [ 190.22569444  153.00347222  155.40798611]
 [ 159.68055556  123.39930556  130.77951389]
 [ 191.859375    152.47395833  153.28645833]
 [ 190.41493056  151.90451389  158.54166667]
 [ 183.015625    142.64236111  148.81944444]
 [ 183.96354167  149.35069444  151.484375  ]
 [ 178.16319444  145.73090278  140.79340278]
 [ 174.78993056  141.36111111  137.6875    ]
 [ 170.36631944  137.66145833  135.22395833]
 [ 160.87847222  134.61458333  128.25694444]
 [ 177.12847222  141.16145833  145.04513889]
 [ 184.13541667  146.17534722  142.94097222]
 [ 175.40104167  139.10416667  139.2447